<?php

namespace bhenk\doc2rst\tag;

class GeneratedTag extends AbstractTag {

    const TAG = "@generated";

    private ?string $description;

    public function getTagName(): string {
        return self::TAG;
    }

    /**
     * Renders the generated tag.
     *
     * ```rst replace & @
     * .. admonition:: syntax
     *
     *    &generated [description]
     * ```
     *
     * @return string
     */
    public function render(): string {
        $this->description = $this->getLine();
        return $this->description;
    }

    /**
     *
     * @generated by IDE
     * @return string|null
     */
    public function getDescription(): ?string {
        return $this->description;
    }

    /**
     * @param string|null $description
     */
    public function setDescription(?string $description): void {
        $this->description = $description;
    }
}